# # # # # # # # # # # # #
#   K i k o - p l u s   #
# # # # # # # # # # # # #

# Basic
name:               "ubirmanz"

author:
#  facebook:         your-id
#  youtubeUser:      your-id
#  youtubeChannel:   your-id
#  twitter:          your-id
#  github:           your-id
#  stackoverflow:    your-id
#  quora:            your-id
#  linkedin:         your-id
#  pinterest:        your-id
#  googlePlus:       your-id
#  instagram:        your-id
#  reddit:           your-id
#  medium:           your-id
#  tumblr:           your-id
#  email:            rioharapan@gmail.com

copyright:
  year:             2017
  name:             Rio Harapan Ps

# Google-analytics
google-analytics:
  id:               "UA-134611589-1"

# Disqus
disqus:
  id:               "harapans"

# URL
url:                "https://rhps.github.io" # the base hostname & protocol for your site
# url:                "http://localhost:4000" # use this url when you develop
baseurl:            "" # the subpath of your site, e.g. /blog


# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:           Asia/Jakarta
permalink:          /blog/:title/

# Pagination
paginate:           10
paginate_path:      "/blog/page:num/"

# Markdown
markdown:           kramdown
kramdown:
  input:            GFM

# Navigation
nav:
  - name:           "About"
    url:            "/about"
  - name:           "Archive"
    url:            "/archive"
  - name:           "Github"
    url:            "https://github.com/AWEEKJ/Kiko-plus"
  - name:           "blog"
    url:            "/blog"

# Sass
sass:
  sass_dir:         _sass
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
gems:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-admin

exclude:            [vendor]