#!/bin/bash
NOW=$(date +"%d%m%Y-%T")
BRed='\033[1;31m'

function commit {
	############
	#Repo Development Repos
	echo $1
	git add . --all
	git commit -m "Commit for : $1 <$NOW>"
	git push -u https://rhps:Cisitu123@github.com/rhps/backend-rhps.github.io.git --all

	############
	#Repo Production Repos
	cd _site/
	git add . --all
	git commit -m "Commit for : $1 <$NOW>"
	git push -u https://rhps:Cisitu123@github.com/rhps/rhps.github.io.git --all	
}

if [[ $1 == "" ]]; then
	echo -e "\033[31mERROR!\033[0m"
	echo "Give Commit Comments"
	echo -e "\033[37mUsing : ./gitpush \"Commit Commentar\"\033[0m"
else
	bundle exec jekyll build site.url
	commit "$1"
	echo -e "\033[37mAll push for Production and Developemt Repository already up-to-date\033[0m"
fi
