-
  Title: ''
  Link: 'https://www.joelonsoftware.com/'
  Description: ''
  Tag:
    - ''
-
  Title: ''
  Link: 'https://www.troyhunt.com/'
  Description: ''
  Tag:
    - ''
-
  Title: ''
  Link: 'http://www.paulgraham.com/'
  Description: ''
  Tag:
    - ''
-
  Title: 'John D Cook Consulting'
  Link: 'https://www.johndcook.com/blog/'
  Description: 'Seorang consultant dibidang modeling mathematics dan privacy, PhD dari University of Texas. Banyak menulis tentang term-term baru dibidang matematika, statistik dan perhitungan numerik, cukup menarik namum kurang membahas secara mendalam'
  Tag:
    - 'mathematics'
    - 'computing'
    - 'privacy'
-
  Title: 'Roland Szabo'
  Link: 'https://rolisz.ro/'
  Description: 'Software engineer yang menulis dengan cukup bagus, mengalir dan menarik. Mostly menulis tentang pengalamannya sehari-hari, bagaimana membangun setup untuk peralatan kerja dan jaringan dirumahnya, pengalaman pribadi dan beberapa review ringan mengenai film, boardgames, perjalanan dan hobbynya, banyak hal dalam tulisannya berisi ayat dari Alkitab. Mantan Googlers'
  Rating: 3
  Tag:
    - 'data-scientist'
    - 'engineer'
    - 'casual'
-
  Title: 'DataGenetics by Nick Berry'
  Link: 'http://datagenetics.com/blog.html'
  Description: 'Nick Berry, ex Microsoft Casual Game team, ex Facebook Data Scientist and masuk dalam list the 50 over 50 in the video games industry, sangat aktif menulis di-blognya, bermacam-macam topik dari data, software engineering hingga fisika. Tuisannya cukup berat'
  Tag:
    - ''
-
  Title: 'BigQuery under the hood'
  Link: 'https://cloud.google.com/blog/products/gcp/bigquery-under-the-hood'
  Description: 'Tehcnology behind Biguery'
  Tag:
    - 'bigquery'
    - 'tech-how-to'
    - 'cloud'
-
  Title: ''
  Link: 'http://gergelyorosz.com/'
  Description: ''
  Tag:
    - ''
-
  Title: ''
  Link: 'https://blog.pragmaticengineer.com/'
  Description: ''
  Tag:
    - ''
-
  Title: ''
  Link: 'https://stopa.io/'
  Description: ''
  Tag:
    - ''
-
  Title: 'Welcome to Jeremiah Collection'
  Link: 'https://jeremiahcollection.com/'
  Description: 'Another inspiration of wood furniture from a fabrication shop based on San Fransisco'
  Tag:
    - ''
-
  Title: 'FlowingData'
  Link: 'https://flowingdata.com/'
  Description: 'FlowingData explores how we use analysis and visualization to understand data and ourselves'
  Tag:
    - ''
-
  Title: 'Nicholas Felton'
  Link: 'http://feltron.com/'
  Description: 'Nicholas Feltron merupakan seorang designer yang membuat karya untuk memvisiualisasikan data dengan indah. Karya-karyanya dapat dinikmati di-websitenye. Feltron menjadi satu-satunya orang yang punya acara Annual meeting setiap tahunnya untuk mempresentasikan karya dan orang-orang mau datang ke Annual Meeting tersebut. Namun ditahun 2014 Annual meeting terakhirnya.'
  Tag:
    - 'data-visualization'
    - 'designer'
    - 'data'
-
  Title: ''
  Link: 'https://usesthis.com/'
  Description: 'Terkadang kita terkagum-kagum dengan kemampuan orang-orang hebat yang begitu produktif, mampu menghasilkan ribuan baris kode perhari atau karya lainnya. Ingin tahu apa saja perlengkapan yang mereka gunakan sehari-hari untuk mendukung kerja mereka, usethis.com secara menarik membeberkannya.'
  Tag:
    - ''
-
  Title: ''
  Link: 'https://odysseyworkshop.org/index.html'
  Description: ''
  Tag:
    - ''
-
  Title: 'Great Scott Gadgets'
  Link: 'https://greatscottgadgets.com/'
  Description: 'Barang-barang oprekan aneh dan mahal'
  Tag: 
    - 'RF'
    - 'hack'
    - 'diy'
-
  Title: ''
  Link: ''
  Description: ''
  Tag:
    - ''
